
# Project name.
name: 'dbt_activity_schema'
version: '0.1.0'
config-version: 2

# See pyproject.toml for details
require-dbt-version: [">=1.3.0"]

# The "profile" dbt uses for this project.
profile: 'dbt_activity_schema'

# Configuration paths.
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
