
# Project Name
name: dbt_activity_schema_integration_tests
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'integration_tests'

config-version: 2

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  +materialized: external
  +format: csv

vars:
  primary_activity_columns:
    - activity_id
    - customer
    - ts
    - activity
    - anonymous_customer_id
    - feature_json
    - revenue_impact
    - link
    - activity_occurrence
    - activity_repeated_at
  appended_activity_columns:
    - feature_json
    - ts

seeds:
  dbt_activity_schema_integration_tests:
    +column_types:
      ACTIVITY_REPEATED_AT: TIMESTAMP
