
# Project Name
name: dbt_activity_schema_integration_tests
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'integration_tests'

config-version: 2

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

target-path: "target"
clean-targets: ["target", "dbt_modules"]

models:
  +materialized: table

vars:
  running_intergration_tests: true
  activity_schema_required_column_aliases:
    ts: ts
    customer: customer
    activity: activity
    activity_occurrence: activity_occurrence
    activity_repeated_at: activity_repeated_at
  activity_schema_primary_activity_columns:
    - customer
    - ts
    - activity_occurrence
    - activity_repeated_at
    - activity_id
    - activity
    - anonymous_customer_id
    - feature_json
    - revenue_impact
    - link
  activity_schema_appended_activities_columns:
    - name: feature_json
      aggregation: min
    - name: ts
      aggregation: min

seeds:
  dbt_activity_schema_integration_tests:
    +column_types:
      ACTIVITY_REPEATED_AT: TIMESTAMP
