config:
    send_anonymous_usage_stats: False
    use_colors: True

integration_tests:
  outputs:
    duckdb:
      type: duckdb
      path: ":memory:"
      database: memory
      external_root: tmp/materialized # Materialize Models as CSV for Inspection
  target: duckdb
